# First things first
* Click **File -> Save a copy in Drive** and click **Open in new tab** in the pop-up window to save your progress in Google Drive.
* Click **Runtime -> Change runtime type** and select **GPU** in Hardware accelerator box to enable faster GPU training.


# If you're using Colab notebook.


In [1]:
try:
    import google.colab
    from google.colab.output import clear as clear_output
    IN_COLAB = True
except:
    IN_COLAB = False
    from IPython.display import clear_output as clear_output



In [2]:
# import required package
from sklearn.metrics import ndcg_score, dcg_score
import numpy as np

In [3]:
# Draw random data.
n = 20
draw_score = lambda up: np.random.randint(0, up, size=(1, n))
draw_score = lambda up: np.random.choice(up, size=(1, n))


In [4]:
# Releveance scores in output order 
relevance_score = draw_score(100)

# Releveance scores in Ideal order 
ideal_relevance = -np.sort(-relevance_score)

print(relevance_score, ideal_relevance, sep="\n")

[[72 21 69 64 66  8 32 51 15 24  1 33 13 42  8 88 52 75 20 61]]
[[88 75 72 69 66 64 61 52 51 42 33 32 24 21 20 15 13  8  8  1]]


In [5]:
# Cumulative Gain
cg = np.sum(relevance_score)
cg


815

In [10]:
def dcg_function(score):
    """
      score: np array of relevance score.
      returns: Discounted Cumulative Gain, float.
    """
    # Generated the np array of log2([2, 3, ..... n+1])
    # x = "Fill in this blank."
    # print(np.log2(x))

    # Divided the score by log value, sum then return.
    # return "Fill in this blank."

In [11]:
# Discounted Cumulative gain
dcg = dcg_function(relevance_score)

# Ideal Discounted Cumulative gain
idcg = dcg_function(ideal_relevance)

dcg, idcg


(309.435245408772, 358.87745165584965)

In [12]:
ndcg = dcg / idcg
ndcg


0.8622309481441288

# Compare with package functions value.




In [13]:
# Because the "dcg_score" function in sklearn takes the ranking position as input, so we cannot use this:
# dcg = dcg_score(ideal_relevance, relevance_score)
# Instead....

order_of_relevance_score = -np.argsort(relevance_score)[:, ::-1] + n

order_of_relevance_score, relevance_score, ideal_relevance

(array([[ 5,  3, 20, 18, 16, 17,  1,  4, 13,  7,  9, 14, 11, 19,  2, 12,
          8, 15,  6, 10]]),
 array([[72, 21, 69, 64, 66,  8, 32, 51, 15, 24,  1, 33, 13, 42,  8, 88,
         52, 75, 20, 61]]),
 array([[88, 75, 72, 69, 66, 64, 61, 52, 51, 42, 33, 32, 24, 21, 20, 15,
         13,  8,  8,  1]]))

In [14]:
# DCG score 

dcg = dcg_score(ideal_relevance, order_of_relevance_score) 
print("DCG score : ", dcg) 
   
# IDCG score 
idcg = dcg_score(ideal_relevance, ideal_relevance) 
print("IDCG score : ", idcg) 
   
# Normalized DCG score 
ndcg = dcg / idcg
print("nDCG score : ", ndcg) 
   
# or we can use the scikit-learn ndcg_score package 
print("nDCG score (from package function) : ",
      ndcg_score(ideal_relevance, relevance_score)) 

DCG score :  309.4352454087719
IDCG score :  358.87745165584965
nDCG score :  0.8622309481441285
nDCG score (from package function) :  0.7643687737160236


### Answers for the dcg function.

In [15]:
def dcg_function(score):
    """
      score: np array of relevance score.
      returns: Discounted Cumulative Gain, float.
    """
    # Generated the np array of log2([2, 3, ..... n+1])
    x = np.asarray(range(score.shape[-1])) + 2

    # Divided the score by log value, sum then return.
    return np.sum(score / np.log2(x))